controller_list:
  - name: fake_vehicle_controller
    joints:
      - base_x_joint
      - base_y_joint
      - base_yaw_joint
      - front_left_wheel
      - front_right_wheel
      - rear_left_wheel
      - rear_right_wheel